=== Shihao-Song/DFSynthesizer/sdf3/fsmsadf/xsd/sdf3-fsmsadf.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="uri:sdf3" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="uri:sdf3" elementFormDefault="qualified">
  <xs:element name="sdf3">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="applicationGraph" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="architectureGraph" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="mapping" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="type" type="xs:string" use="required"/>
      <xs:attribute name="version" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>
  <!-- 
        applicationGraph
  -->
  <xs:element name="applicationGraph">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="fsmsadf" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="fsmsadfProperties" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="fsm" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="fsmsadf">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="scenariograph" maxOccurs="unbounded" minOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="actor" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="port" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                        <xs:attribute name="type" type="xs:string" use="required"/>
                        <xs:attribute name="rate" type="xs:decimal" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:string" use="required"/>
                  <xs:attribute name="type" type="xs:string"/>
                  <xs:attribute name="size" type="xs:decimal"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="channel" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:attribute name="name" type="xs:string" use="required"/>
                  <xs:attribute name="srcActor" type="xs:string"/>
                  <xs:attribute name="srcPort" type="xs:string"/>
                  <xs:attribute name="dstActor" type="xs:string"/>
                  <xs:attribute name="dstPort" type="xs:string"/>
                  <xs:attribute name="initialTokens" type="xs:decimal"/>
                  <xs:attribute name="size" type="xs:decimal"/>
                  <xs:attribute name="nrConnections" type="xs:decimal"/>
                  <xs:attribute name="inBandwidth" type="xs:double"/>
                  <xs:attribute name="outBandwidth" type="xs:double"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="type" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="fsmsadfProperties">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="defaultProperties" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="scenarios" maxOccurs="1" minOccurs="1"/>
        <xs:element ref="graphProperties" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="defaultProperties">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="actorProperties" maxOccurs="unbounded" minOccurs="1"/>
        <xs:element ref="channelProperties" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="scenarios">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="scenario" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="actorProperties" maxOccurs="unbounded" minOccurs="0"/>
              <xs:element ref="channelProperties" maxOccurs="unbounded" minOccurs="0"/>
              <xs:element ref="storageDistributions" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="graph" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="actorProperties">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="processor" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="port" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="type" type="xs:string" use="optional"/>
            <xs:attribute name="rate" type="xs:decimal" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="actor" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="processor">
    <xs:complexType>
      <xs:choice>
        <xs:sequence>
          <xs:element name="executionTime" minOccurs="1" maxOccurs="1">
            <xs:complexType>
              <xs:attribute name="time" type="xs:decimal" use="required"/>
            </xs:complexType>
          </xs:element>
          <xs:element ref="memory" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:sequence>
          <xs:element ref="arbitration"/>
        </xs:sequence>
      </xs:choice>
      <xs:attribute name="type" type="xs:string"/>
      <xs:attribute name="default" type="xs:string"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="timeslice" type="xs:decimal"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="memory">
    <xs:complexType>
      <xs:choice>
        <xs:sequence>
          <xs:element ref="stateSize" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
        <xs:sequence>
          <xs:element name="actor" maxOccurs="unbounded" minOccurs="0">
            <xs:complexType>
              <xs:attribute name="name" type="xs:string" use="required"/>
              <xs:attribute name="processorType" type="xs:string" use="required"/>
            </xs:complexType>
          </xs:element>
          <xs:element name="channel" maxOccurs="unbounded" minOccurs="0">
            <xs:complexType>
              <xs:attribute name="name" type="xs:string" use="required"/>
              <xs:attribute name="in" type="xs:boolean" use="required"/>
              <xs:attribute name="out" type="xs:boolean" use="required"/>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
      </xs:choice>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="size" type="xs:decimal"/>
      <xs:attribute name="type" type="memoryType"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="stateSize">
    <xs:complexType>
      <xs:attribute name="max" type="xs:decimal" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="storageDistributions">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="storageDistribution" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="storageDistribution">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="channel" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="sz" type="xs:decimal" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="sz" type="xs:decimal" use="required"/>
      <xs:attribute name="thr" type="xs:double" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="channelProperties">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="bufferSize" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="tokenSize" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="bandwidth" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="latency" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="channel" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="bufferSize">
    <xs:complexType>
      <xs:attribute name="src" type="xs:decimal" use="required"/>
      <xs:attribute name="dst" type="xs:decimal" use="required"/>
      <xs:attribute name="mem" type="xs:decimal" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="tokenSize">
    <xs:complexType>
      <xs:attribute name="sz" type="xs:decimal" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="bandwidth">
    <xs:complexType>
      <xs:attribute name="min" type="xs:double" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="latency">
    <xs:complexType>
      <xs:attribute name="min" type="xs:decimal" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="graphProperties">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="timeConstraints" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="timeConstraints">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="throughput" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="throughput" type="xs:double"/>
  <xs:element name="arbitration">
    <xs:complexType>
      <xs:attribute name="type" type="xs:string" use="required"/>
      <xs:attribute name="wheelsize" type="xs:decimal" use="required"/>
      <xs:attribute name="contextSwitchOverhead" type="xs:decimal" use="required"/>
      <xs:attribute name="slotLength" type="xs:decimal" use="optional"/>
      <xs:attribute name="preemptive" type="xs:boolean" use="required"/>
    </xs:complexType>
  </xs:element>
  <!-- Finite state machine -->
  <xs:element name="fsm">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="state" maxOccurs="unbounded" minOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="transition" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                  <xs:attribute name="destination" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="scenario" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="initialstate" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <!--
        Architecture Graph
        -->
  <xs:element name="architectureGraph">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="tile" type="ArchTile" maxOccurs="unbounded" minOccurs="1"/>
        <xs:element name="connection" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="srcTile" type="xs:string"/>
            <xs:attribute name="srcNetworkInterface" type="xs:string"/>
            <xs:attribute name="dstTile" type="xs:string"/>
            <xs:attribute name="dstNetworkInterface" type="xs:string"/>
            <xs:attribute name="delay" type="xs:decimal"/>
            <xs:attribute name="latency" type="xs:decimal"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="ArchTile">
    <xs:sequence>
      <xs:element ref="processor" minOccurs="0" maxOccurs="1"/>
      <xs:element ref="memory" minOccurs="1" maxOccurs="unbounded"/>
      <xs:element ref="networkInterface" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
  </xs:complexType>
  <xs:element name="networkInterface">
    <xs:complexType>
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:attribute name="nrInConnections" type="xs:decimal"/>
      <xs:attribute name="nrOutConnections" type="xs:decimal"/>
      <xs:attribute name="inBandwidth" type="xs:double"/>
      <xs:attribute name="outBandwidth" type="xs:double"/>
    </xs:complexType>
  </xs:element>
  <!--
        Mapping
  -->
  <xs:element name="mapping">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="scenario" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="tile" type="MappingTile" minOccurs="0" maxOccurs="unbounded"/>
              <xs:element name="connection" type="MappingConnection" minOccurs="0" maxOccurs="unbounded">
             </xs:element>
              <xs:element name="constraints" minOccurs="0" maxOccurs="1">
                </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="resourceUsage" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="tile" type="MappingTile" minOccurs="0" maxOccurs="unbounded"/>
              <xs:element name="connection" type="BaseClass" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="appGraph" type="xs:string"/>
      <xs:attribute name="archGraph" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <!-- 
        tile used in the mapping
  -->
  <xs:complexType name="MappingTile">
    <xs:sequence>
      <xs:element name="processor" type="MappingProcessor" minOccurs="0" maxOccurs="1"/>
      <xs:element name="memory" type="MappingTileMemory" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="networkInterface" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
  </xs:complexType>
  <xs:complexType name="MappingProcessor">
    <xs:sequence>
      <xs:element name="actor" type="BaseClass" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="arbitration" minOccurs="0" maxOccurs="1">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="schedule" minOccurs="0" maxOccurs="1">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="state" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                      <xs:attribute name="actor" type="xs:string" use="required"/>
                      <xs:attribute name="startOfPeriodicRegime" type="xs:boolean" use="optional"/>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
          <xs:attribute name="timeslice" type="xs:decimal" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
  </xs:complexType>
  <!-- mapping/tile/memory -->
  <xs:complexType name="MappingTileMemory">
    <xs:complexContent>
      <xs:extension base="BaseClass">
        <xs:sequence>
          <xs:element name="actor" type="MappingTileMemoryActor" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element name="channel" type="MappingTileMemoryChannel" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <!-- this one is used in the initial -->
        <xs:attribute name="size" type="xs:decimal" use="optional"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="MappingTileMemoryActor">
    <xs:complexContent>
      <xs:extension base="BaseClass">
        <xs:attribute name="processorType" type="xs:string" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="MappingTileMemoryChannel">
    <xs:complexContent>
      <xs:extension base="BaseClass">
        <xs:attribute name="bufferType" type="bufferType" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <!-- mapping/connection-->
  <xs:complexType name="MappingConnection">
    <xs:complexContent>
      <xs:extension base="BaseClass">
        <xs:sequence>
          <xs:element name="channel" type="BaseClass" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <!--
    base class, complex class with name attribute.
  -->
  <xs:complexType name="BaseClass">
    <xs:attribute name="name" type="xs:string" use="required"/>
  </xs:complexType>
  <!--
        Type defenitions
   -->
  <!-- The type of memory, sdf3 now supports commin, commout, shared, instr and data -->
  <xs:simpleType name="memoryType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="commout"/>
      <xs:enumeration value="commin"/>
      <xs:enumeration value="data"/>
      <xs:enumeration value="instr"/>
      <xs:enumeration value="shared"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="bufferType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="dst"/>
      <xs:enumeration value="src"/>
      <xs:enumeration value="shared"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== Shihao-Song/DFSynthesizer/sdf3/fsmsadf/test/models/mp3decoder.xml
<?xml version='1.0' encoding='UTF-8'?>
<sdf3 type='fsmsadf' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' 
    xmlns='uri:sdf3' version='1.0' 
    xsi:schemaLocation='uri:sdf3 http://www.es.ele.tue.nl/sdf3/xsd/sdf3-fsmsadf.xsd'>
    <applicationGraph name='mp3decoder'>
        <fsmsadf>
          <scenariograph name='mp3decoder-ll' type='MP3DECODER-LL'>
            <actor name="Feed" type="Feed" repetitions="0">
              <port name="Out_FD2SP" type="out" rate="1"></port>
              <!--<port name="Self_In" type="in" rate="1"></port>
              <port name="Self_Out" type="out" rate="1"></port>-->
              <!--<port name="SC_In" type="in" rate="2"></port>-->
            </actor>
            <actor name="Play" type="Play" repetitions="2">
              <port name="In_WB2PL" type="in" rate="1"></port>
              <port name="Self_In" type="in" rate="1"></port>
              <port name="Self_Out" type="out" rate="1"></port>
              <!--<port name="SC_In" type="in" rate="1"></port>-->
            </actor>
            <actor name="Splitter" type="Splitter" repetitions="1">
              <port name="In_FD2SP" type="in" rate="1"></port>
              <port name="Out_SP2RQR" type="out" rate="2"></port>
              <port name="Out_SP2RQL" type="out" rate="2"></port>
              <port name="Res2_In" type="in" rate="1"></port>
            </actor>
            <actor name="ReQuantizationLeft" type="ReQuantizationLeft" repetitions="2">
              <port name="In_SP2RQL" type="in" rate="1"></port>
              <port name="Out_RQL2S" type="out" rate="1"></port>
              <port name="Res_In" type="in" rate="1"></port>
              <port name="Res_Out" type="out" rate="1"></port>
            </actor>
            <actor name="ReQuantizationRight" type="ReQuantizationRight" repetitions="2">
              <port name="In_SP2RQR" type="in" rate="1"></port>
              <port name="Out_RQR2S" type="out" rate="1"></port>
              <port name="Res_In" type="in" rate="1"></port>
            </actor>
            <actor name="Stereo" type="Stereo" repetitions="2">
              <port name="In_RQR2S" type="in" rate="1"></port>
              <port name="In_RQL2S" type="in" rate="1"></port>
              <port name="Out_S2AAR" type="out" rate="32"></port>
              <port name="Out_S2AAL" type="out" rate="32"></port>
              <port name="Res_Out" type="out" rate="1"></port>
              <port name="Res2_Out" type="out" rate="1"></port>
              <!--<port name="DummyL_Out" type="out" rate="1"></port>
              <port name="DummyR_Out" type="out" rate="1"></port>-->
            </actor>
            <actor name="ParkDec" type="ParkDec" repetitions="0">
              <port name="Self_Out" type="out" rate="1"></port>
              <port name="Self_In" type="in" rate="1"></port>
            </actor>
            <actor name="Sync1" type="Sync1" repetitions="1">
              <port name="Res2_In" type="in" rate="2"></port>
              <port name="Res2_Out" type="out" rate="1"></port>
            </actor>
            <actor name="AntiAliasLeft" type="AntiAliasLeft" repetitions="64">
              <port name="In_S2AAL" type="in" rate="1"></port>
              <port name="Out_AAL2IDL" type="out" rate="1"></port>
              <port name="Res1_In" type="in" rate="1"></port>
              <port name="Res32_In" type="in" rate="1"></port>
            </actor>
            <actor name="AntiAliasRight" type="AntiAliasRight" repetitions="64">
              <port name="In_S2AAR" type="in" rate="1"></port>
              <port name="Out_AAR2IDR" type="out" rate="1"></port>
              <port name="Res1_In" type="in" rate="1"></port>
              <port name="Res32_In" type="in" rate="1"></port>
            </actor>
            <actor name="IMDCTLeft" type="IMDCTLeft" repetitions="64">
              <port name="In_AAL2IDL" type="in" rate="1"></port>
              <port name="Out_IDL2FIL" type="out" rate="1"></port>
            </actor>
            <actor name="IMDCTRight" type="IMDCTRight" repetitions="64">
              <port name="In_AAR2IDR" type="in" rate="1"></port>
              <port name="Out_IDR2FIR" type="out" rate="1"></port>
            </actor>
            <actor name="FrequencyInversionLeft" type="FrequencyInversionLeft" repetitions="64">
              <port name="In_IDL2FIL" type="in" rate="1"></port>
              <port name="Out_FIL2PSL" type="out" rate="1"></port>
              <port name="Res1_Out" type="out" rate="1"></port>
            </actor>
            <actor name="FrequencyInversionRight" type="FrequencyInversionRight" repetitions="64">
              <port name="In_IDR2FIR" type="in" rate="1"></port>
              <port name="Out_FIR2PSR" type="out" rate="1"></port>
              <port name="Res1_Out" type="out" rate="1"></port>
            </actor>
            <actor name="PolySynthLeft" type="PolySynthLeft" repetitions="2">
              <port name="In_FIL2PSL" type="in" rate="32"></port>
              <port name="Out_PSL2WB" type="out" rate="1"></port>
              <port name="Res32_Out" type="out" rate="1"></port>
            </actor>
            <actor name="PolySynthRight" type="PolySynthRight" repetitions="2">
              <port name="In_FIR2PSR" type="in" rate="32"></port>
              <port name="Out_PSR2WB" type="out" rate="1"></port>
            </actor>
            <actor name="WriteBack" type="WriteBack" repetitions="2">
              <port name="In_PSR2WB" type="in" rate="1"></port>
              <port name="In_PSL2WB" type="in" rate="1"></port>
              <port name="Out_WB2PL" type="out" rate="1"></port>
              <port name="Res32_Out" type="out" rate="1"></port>
            </actor>
            <actor name="Sync2" type="Sync2" repetitions="2">
              <port name="Res32_In" type="in" rate="1"></port>
              <port name="Res32_Out" type="out" rate="32"></port>
            </actor>
            <actor name="Sync3" type="Sync3" repetitions="2">
              <port name="Res32_In" type="in" rate="1"></port>
              <port name="Res32_Out" type="out" rate="32"></port>
            </actor>
            <!--<channel name="Self_Feed" srcActor="Feed" srcPort="Self_Out" dstActor="Feed" dstPort="Self_In" initialTokens="1" persistentTokenNames="start" finalTokens="1" persistentFinalTokenNames="start"></channel>-->
            <channel name="FD2SP" srcActor="Feed" srcPort="Out_FD2SP" dstActor="Splitter" dstPort="In_FD2SP" initialTokens="1" persistentTokenNames="start" finalTokens="0" />
            <channel name="Res1_SY12SP" srcActor="Sync1" srcPort="Res2_Out" dstActor="Splitter" dstPort="Res2_In" initialTokens="1" persistentTokenNames="B" finalTokens="1" persistentFinalTokenNames="B"></channel>
            <channel name="Res2_PSL2SY2" srcActor="PolySynthLeft" srcPort="Res32_Out" dstActor="Sync2" dstPort="Res32_In" initialTokens="1" persistentTokenNames="C" finalTokens="1" persistentFinalTokenNames="C"></channel>
            <channel name="Res3_WB2SY3" srcActor="WriteBack" srcPort="Res32_Out" dstActor="Sync3" dstPort="Res32_In" initialTokens="1" persistentTokenNames="D" finalTokens="1" persistentFinalTokenNames="D"></channel>
            <channel name="Self_Play" srcActor="Play" srcPort="Self_Out" dstActor="Play" dstPort="Self_In" initialTokens="1" persistentTokenNames="play" finalTokens="1" persistentFinalTokenNames="play"></channel>
            <channel name="Res1_S2RQL" srcActor="Stereo" srcPort="Res_Out" dstActor="ReQuantizationLeft" dstPort="Res_In" initialTokens="1"></channel>
            <channel name="Res2_FIL2AAL" srcActor="FrequencyInversionLeft" srcPort="Res1_Out" dstActor="AntiAliasLeft" dstPort="Res1_In" initialTokens="1"></channel>
            <channel name="Res3_FIR2AAR" srcActor="FrequencyInversionRight" srcPort="Res1_Out" dstActor="AntiAliasRight" dstPort="Res1_In" initialTokens="1"></channel>
            <channel name="ParkVLDToken" srcActor="ParkDec" srcPort="Self_Out" dstActor="ParkDec" dstPort="Self_In" initialTokens="1" persistentTokenNames="Dec" finalTokens="1" persistentFinalTokenNames="Dec"></channel>
            <!--<channel name="S2DL" srcActor="Stereo" srcPort="DummyL_Out" dstActor="DummyL" dstPort="Stereo_In"></channel>
            <channel name="S2DR" srcActor="Stereo" srcPort="DummyR_Out" dstActor="DummyR" dstPort="Stereo_In"></channel>-->
            <channel name="SP2RQL" srcActor="Splitter" srcPort="Out_SP2RQL" dstActor="ReQuantizationLeft" dstPort="In_SP2RQL"></channel>
            <channel name="SP2RQR" srcActor="Splitter" srcPort="Out_SP2RQR" dstActor="ReQuantizationRight" dstPort="In_SP2RQR"></channel>
            <channel name="RQL2S" srcActor="ReQuantizationLeft" srcPort="Out_RQL2S" dstActor="Stereo" dstPort="In_RQL2S"></channel>
            <channel name="Res1_RQL2RQR" srcActor="ReQuantizationLeft" srcPort="Res_Out" dstActor="ReQuantizationRight" dstPort="Res_In"></channel>
            <channel name="RQR2S" srcActor="ReQuantizationRight" srcPort="Out_RQR2S" dstActor="Stereo" dstPort="In_RQR2S"></channel>
            <channel name="Res1_S2SY1" srcActor="Stereo" srcPort="Res2_Out" dstActor="Sync1" dstPort="Res2_In"></channel>
            <channel name="S2AAL" srcActor="Stereo" srcPort="Out_S2AAL" dstActor="AntiAliasLeft" dstPort="In_S2AAL"></channel>
            <channel name="S2AAR" srcActor="Stereo" srcPort="Out_S2AAR" dstActor="AntiAliasRight" dstPort="In_S2AAR"></channel>
            <channel name="AAL2IDL" srcActor="AntiAliasLeft" srcPort="Out_AAL2IDL" dstActor="IMDCTLeft" dstPort="In_AAL2IDL"></channel>
            <channel name="AAR2IDR" srcActor="AntiAliasRight" srcPort="Out_AAR2IDR" dstActor="IMDCTRight" dstPort="In_AAR2IDR"></channel>
            <channel name="IDL2FIL" srcActor="IMDCTLeft" srcPort="Out_IDL2FIL" dstActor="FrequencyInversionLeft" dstPort="In_IDL2FIL"></channel>
